### ISSUE TITLE
CNL-Decryptor doesn´t install on Mypal68 Browser for XP, XP64 & Vista systems (based on Firefox68)

### ISSUE THREAD

**Issue by PLudkovski** [Brawl345/CNL-decryptor#2]
Hello Andreas !

CNL-Decryptor doesn´t install on Mypal68 Browser for XP, XP64 & Vista systems (based on Firefox68).
What is the minimum Firefox version to install CNL-Decryptor ?

And can anything be done, to install CNL-Decryptor on a lower Firefox version?
I really would like to try it out, but i don´t know how to do :-(

If you don´t mind, can you try it yourself with Mypal68 Browser, if there is a way?
(there is no install-setup, the install rar will unzip to a folder, which can easily be deleted and removed)
The creator of Mypal68 is Feodor2 here on Github.

Many thanks for considering.

**Comment by Brawl345** [comment]
The "minimum supported Firefox version" is the latest currently supported official Firefox version by Mozilla. Mypal68 seems to be a very outdated browser based on a release from 2019 and lacks the necessary APIs. Running such outdated browser is a major security risk and I would strongly recommend not to do it. So nothing I can do.
