### ISSUE TITLE
Option to set "open in new tab or pop-up" or different new tab behavior.

### ISSUE THREAD

**Issue by Lumbago1337** [Brawl345/CNL-decryptor#3]
Hi,

Is it possible to give us an option to choose whether the links open in a new tab or a new pop-up window?
I was happy with the pop-up window in the last version. The new tab opens as a far right tab. When I close the tab, it doesn't jump back to the last tab I was in (which was somewhere on the far left, with other tabs in between).
I am using the latest Firefox (Desktop Version), if that matters.

Thanks for the add-on!

**Comment by 514guy** [comment]
I second this. Perhaps a new tab result is debatably better for FF Android, but on FF desktop I rolled the extension back to 2.1.1 and blocked its automatic updates.

**Comment by Brawl345** [comment]
v2.3.0 now supports this, check the add-on settings. Firefox is already published, Chrome takes a bit.
