### ISSUE TITLE
MacOs Firefox

### ISSUE THREAD

**Issue by JanLouisP** [Brawl345/CNL-decryptor#4]
Hello :),

It is not opening the tab with the links anymore for me on MacOs using Firefox.

**Comment by JanLouisP** [comment]
Okey, nvm, PupUp is working :).

**Comment by Brawl345** [comment]
Does it work now? It should still work with a tab, you change it in the addon settings.

**Comment by JanLouisP** [comment]
No, only the Pupup works, the Tab is not working, when I select it in the settings.

**Comment by Brawl345** [comment]
I pushed v2.3.1. It's a blind fix since I can't reproduce it on macOS :/

**Comment by JanLouisP** [comment]
It works now, sry that I cannot offer more usefull Info.

**Comment by Brawl345** [comment]
So it works now with a tab with the new version? Thank you very much for reporting!

**Comment by JanLouisP** [comment]
Yes, Tab is working on 2.3.1. Thank you! 🫶
